### ISSUE TITLE
Check and remove redundant titles

### ISSUE THREAD

**Issue by mewim** [kuzudb/kuzu-blog#21]
I noted that a few blog posts, such as https://blog.kuzudb.com/post/kuzu-0.0.8-release/ and https://blog.kuzudb.com/post/meet-kuzu/ has two titles.

<img width="1418" alt="Screenshot 2024-03-05 at 9 57 25 PM" src="https://github.com/kuzudb/kuzu-blog/assets/14037726/bcaf8902-5f9e-4c02-9a4f-007bec68a69d">

We should check all blogs to see if there are other posts with similar issue and fix them all.

**Comment by prrao87** [comment]
Will do!
